CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  query TEXT NOT NULL,
  result TEXT NOT NULL,
  lat DECIMAL(9,6) NOT NULL,
  lng DECIMAL(9,6) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);